include(CMakeDependentOption)

string(TOUPPER "${PROJECT_NAME}" PROJECT_NAME_UPPERCASE)

cmake_dependent_option(
	"${PROJECT_NAME_UPPERCASE}_STATIC_BUILD"
	"Build ${PROJECT_NAME} as a static library"
	ON
	"NOT BUILD_SHARED_LIBS"
	OFF
)

set(THIS_PROJECT_BUILD_STATIC ${${PROJECT_NAME_UPPERCASE}_STATIC_BUILD})

if(THIS_PROJECT_BUILD_STATIC)
	set("${PROJECT_NAME_UPPERCASE}_BUILD_TYPE" STATIC)
else()
	set("${PROJECT_NAME_UPPERCASE}_BUILD_TYPE" SHARED)
	set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
endif()
